apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/lua-resty-waf: "active"
spec:
  tls:
  - hosts:
    - '*.desertbluffs.com'
    - desertbluffs.com
    secretName: desertbluffs-tls
  rules:
  - host: a.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: deluge
          servicePort: deluge
  - host: b.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: pms
          servicePort: webtools
  - host: c.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: nzbget
          servicePort: nzbget
  - host: d.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: tautulli
          servicePort: tautulli
  - host: f.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: radarr
          servicePort: radarr
  - host: g.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: smokeping
          servicePort: smokeping
  - host: h.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: sonarr
          servicePort: sonarr
  - host: i.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: nzbhydra
          servicePort: nzbhydra
  - host: j.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: radarr4k
          servicePort: radarr4k
  - host: m.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: grafana
