apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: noauth
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/lua-resty-waf: "active"
spec:
  tls:
  - hosts:
    - '*.desertbluffs.com'
    - desertbluffs.com
    secretName: desertbluffs-tls
  rules:
  - http: &oauth2_proxy
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: oauth2-proxy
  - host: a.desertbluffs.com
    http: *oauth2_proxy
  - host: b.desertbluffs.com
    http: *oauth2_proxy
  - host: c.desertbluffs.com
    http: *oauth2_proxy
  - host: d.desertbluffs.com
    http: *oauth2_proxy
  - host: f.desertbluffs.com
    http: *oauth2_proxy
  - host: g.desertbluffs.com
    http: *oauth2_proxy
  - host: h.desertbluffs.com
    http: *oauth2_proxy
  - host: i.desertbluffs.com
    http: *oauth2_proxy
  - host: j.desertbluffs.com
    http: *oauth2_proxy
  - host: m.desertbluffs.com
    http: *oauth2_proxy
